@startuml
'https://plantuml.com/class-diagram

entity User {
    * user_id: int unsigned <<generated>>
    --
    * user_name: varchar(50)
}

entity TwitterUser {
	* twitter_user_id: int unsigned <<generated>>
	--
	* user_id: int unsigned <<foreign key>>
	* twitter_id: varchar(255)
	* screen_name: varchar(255)
	* access_token: varchar(255)
	* token_secret: varchar(255)
}

User ||-|| TwitterUser

entity UserFollow {
    * user_follow_id: int unsigned <<generated>>
    * from_user_id: int unsigned
    * to_user_id: int unsigned
}

User ||-o{ UserFollow

entity RuleBook {
    * rule_book_id: int unsigned <<generated>>
    --
    * rule_book_name: varchar(255)
}

entity RuleBookDictionary {
    * rule_book_dictionary_id: int unsigned <<generated>>
    --
    * rule_book_id: int unsigned <<foreign key>>
    * rule_book_name: varchar(255)
}

RuleBook ||-|{ RuleBookDictionary

entity Scenario {
    * scenario_id: int unsigned <<generated>>
    --
    * scenario_name: varchar(255)
    * scenario_type: varchar(50)
    rule_book_id: int unsigned <<foreign key>>
}

entity ScenarioDictionary {
    * scenario_dictionary_id: int unsigned <<generated>>
    --
    * scenario_id: int unsigned <<foreign key>>
    * scenario_name: varchar(255) <<unique>>
}

Scenario ||--|{ ScenarioDictionary
Scenario }|--o| RuleBook

entity Participate {
    * participate_id: int unsigned <<generated>>
    --
    * scenario_id: int unsigned <<foreign key>>
    * user_id: int unsigned <<foreign key>>
    * disp_order: int unsigned
}

User ||--o{ Participate
Scenario ||--o{ Participate

entity ParticipateRole {
    * participate_role_id: int unsigned <<generated>>
    --
    * participate_id: int unsigned <<foreign key>>
    * participate_role_type: varchar(50)
}

Participate ||--|{ ParticipateRole

entity ParticipateImpression {
	* participate_impression_id: int unsigned <<generated>>
	--
	* participate_id: int unsigned <<foreign key>>
	* has_spoiler: boolean
	* disclosure_range: varchar(50)
	* impression: text
}

Participate ||--o| ParticipateImpression
@enduml