spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stukerdb?characterEncoding=UTF-8
    username: stuker # 本番は起動引数で与える
    password: scenar10 # 本番は起動引数で与える
    driverClassName: com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
  messages:
    basename: messages
    cache-duration: -1
    encoding: UTF-8
  jackson:
    property-naming-strategy: SNAKE_CASE
security:
  corsClientUrls:
    - http://localhost:3000
server:
  port: 8091
  servlet:
    context-path: /scenario-tuker
    session:
      timeout: 86400
  compression:
    enabled: true
  tomcat:
    remoteip.remote-ip-header: true
    use-forward-headers: true
logging:
  level:
    org.springframework: INFO
    root: INFO
    org.seasar.dbflute: ERROR
  file.name: /var/log/scenario-tuker.log

firebase:
  adminsdk:
    secretkey:
      path: ""
  database:
    url: ""