name: delivery

on:
  push:
    branches:
      - main

jobs:
  delivery:
    runs-on: [ self-hosted ]
    steps:
      - name: clone repository
        uses: actions/checkout@v2

      - name: download arm64 JDK 11
        run: |
          download_url="https://aka.ms/download-jdk/microsoft-jdk-11.0.13.8.1-linux-aarch64.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '11'
          architecture: arm64

      - name: build
        run: |
          ./gradlew jibDockerBuild
      - name: deploy
        run: |
          docker login ghcr.io -u h-orito -p ${{ secrets.PACKAGE_PAT }}
          docker push ghcr.io/h-orito/scenario-tuker
      - name: release
        run: |
          kubectl delete pod -l app=scenario-tuker